# Generated by Django 4.2.4 on 2023-10-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crossword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('crossword', models.CharField(max_length=131072)),
                ('describe', models.CharField(max_length=131072)),
                ('link', models.CharField(max_length=64, unique=True)),
                ('crator_id', models.IntegerField()),
                ('status', models.IntegerField()),
                ('lang', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=64)),
                ('second_name', models.CharField(max_length=64)),
                ('crosswords_id', models.CharField(max_length=10000)),
                ('sign_up_time', models.CharField(max_length=30)),
            ],
        ),
    ]
