# Generated by Django 4.2.4 on 2023-10-29 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crossword',
            new_name='Crosswords',
        ),
    ]
