# Generated by Django 4.2.7 on 2023-11-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0005_rename_craetor_id_crosswords_creator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crosswords',
            name='status',
            field=models.CharField(max_length=1),
        ),
    ]
