# Generated by Django 4.2.7 on 2023-11-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0006_alter_crosswords_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crosswords',
            name='posting_time',
        ),
        migrations.RemoveField(
            model_name='users',
            name='crosswords_id',
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='crosswords',
            name='language',
            field=models.CharField(max_length=5),
        ),
    ]
